apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: hello
  serviceAccountName: argo-workflow
  templates:
    - name: hello
      container:
        image: alpine:3.18
        command: [sh, -c]
        args: ["echo Hello Argo World"]
